language: 
    - r
    - python

sudo: required

r_packages:
    - rmarkdown

before_install:
    - sudo pip install cookiecutter
    - cookiecutter . --no-input repo_name=boilerplate
    - cd ./boilerplate
